// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: twopc.proto

package org.h2.twopc;

public interface TwoPCResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:twopc.TwoPCResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   * @return The reply.
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   * @return The bytes for reply.
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
