// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: twopc.proto

package org.h2.twopc;

/**
 * <pre>
 * The request message with command
 * </pre>
 *
 * Protobuf type {@code twopc.TwoPCRequest}
 */
public  final class TwoPCRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:twopc.TwoPCRequest)
    TwoPCRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TwoPCRequest.newBuilder() to construct.
  private TwoPCRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TwoPCRequest() {
    command_ = "";
    db_ = "";
    table_ = "";
    sid_ = "";
    tid_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TwoPCRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TwoPCRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            command_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            db_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            table_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sid_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            tid_ = s;
            break;
          }
          case 50: {

            data_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.h2.twopc.TwoPCProto.internal_static_twopc_TwoPCRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.h2.twopc.TwoPCProto.internal_static_twopc_TwoPCRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.h2.twopc.TwoPCRequest.class, org.h2.twopc.TwoPCRequest.Builder.class);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  private volatile java.lang.Object command_;
  /**
   * <code>string command = 1;</code>
   * @return The command.
   */
  public java.lang.String getCommand() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      command_ = s;
      return s;
    }
  }
  /**
   * <code>string command = 1;</code>
   * @return The bytes for command.
   */
  public com.google.protobuf.ByteString
      getCommandBytes() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      command_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DB_FIELD_NUMBER = 2;
  private volatile java.lang.Object db_;
  /**
   * <code>string db = 2;</code>
   * @return The db.
   */
  public java.lang.String getDb() {
    java.lang.Object ref = db_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      db_ = s;
      return s;
    }
  }
  /**
   * <code>string db = 2;</code>
   * @return The bytes for db.
   */
  public com.google.protobuf.ByteString
      getDbBytes() {
    java.lang.Object ref = db_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      db_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object table_;
  /**
   * <code>string table = 3;</code>
   * @return The table.
   */
  public java.lang.String getTable() {
    java.lang.Object ref = table_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      table_ = s;
      return s;
    }
  }
  /**
   * <code>string table = 3;</code>
   * @return The bytes for table.
   */
  public com.google.protobuf.ByteString
      getTableBytes() {
    java.lang.Object ref = table_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      table_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SID_FIELD_NUMBER = 4;
  private volatile java.lang.Object sid_;
  /**
   * <code>string sid = 4;</code>
   * @return The sid.
   */
  public java.lang.String getSid() {
    java.lang.Object ref = sid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sid_ = s;
      return s;
    }
  }
  /**
   * <code>string sid = 4;</code>
   * @return The bytes for sid.
   */
  public com.google.protobuf.ByteString
      getSidBytes() {
    java.lang.Object ref = sid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TID_FIELD_NUMBER = 5;
  private volatile java.lang.Object tid_;
  /**
   * <pre>
   *TODO: change tid to long
   * </pre>
   *
   * <code>string tid = 5;</code>
   * @return The tid.
   */
  public java.lang.String getTid() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *TODO: change tid to long
   * </pre>
   *
   * <code>string tid = 5;</code>
   * @return The bytes for tid.
   */
  public com.google.protobuf.ByteString
      getTidBytes() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 6;</code>
   * @return The data.
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCommandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, command_);
    }
    if (!getDbBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, db_);
    }
    if (!getTableBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, table_);
    }
    if (!getSidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sid_);
    }
    if (!getTidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tid_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(6, data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCommandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, command_);
    }
    if (!getDbBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, db_);
    }
    if (!getTableBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, table_);
    }
    if (!getSidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sid_);
    }
    if (!getTidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tid_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.h2.twopc.TwoPCRequest)) {
      return super.equals(obj);
    }
    org.h2.twopc.TwoPCRequest other = (org.h2.twopc.TwoPCRequest) obj;

    if (!getCommand()
        .equals(other.getCommand())) return false;
    if (!getDb()
        .equals(other.getDb())) return false;
    if (!getTable()
        .equals(other.getTable())) return false;
    if (!getSid()
        .equals(other.getSid())) return false;
    if (!getTid()
        .equals(other.getTid())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + getCommand().hashCode();
    hash = (37 * hash) + DB_FIELD_NUMBER;
    hash = (53 * hash) + getDb().hashCode();
    hash = (37 * hash) + TABLE_FIELD_NUMBER;
    hash = (53 * hash) + getTable().hashCode();
    hash = (37 * hash) + SID_FIELD_NUMBER;
    hash = (53 * hash) + getSid().hashCode();
    hash = (37 * hash) + TID_FIELD_NUMBER;
    hash = (53 * hash) + getTid().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.h2.twopc.TwoPCRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.h2.twopc.TwoPCRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.h2.twopc.TwoPCRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.h2.twopc.TwoPCRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.h2.twopc.TwoPCRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message with command
   * </pre>
   *
   * Protobuf type {@code twopc.TwoPCRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:twopc.TwoPCRequest)
      org.h2.twopc.TwoPCRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.h2.twopc.TwoPCProto.internal_static_twopc_TwoPCRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.h2.twopc.TwoPCProto.internal_static_twopc_TwoPCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.h2.twopc.TwoPCRequest.class, org.h2.twopc.TwoPCRequest.Builder.class);
    }

    // Construct using org.h2.twopc.TwoPCRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      command_ = "";

      db_ = "";

      table_ = "";

      sid_ = "";

      tid_ = "";

      data_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.h2.twopc.TwoPCProto.internal_static_twopc_TwoPCRequest_descriptor;
    }

    @java.lang.Override
    public org.h2.twopc.TwoPCRequest getDefaultInstanceForType() {
      return org.h2.twopc.TwoPCRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.h2.twopc.TwoPCRequest build() {
      org.h2.twopc.TwoPCRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.h2.twopc.TwoPCRequest buildPartial() {
      org.h2.twopc.TwoPCRequest result = new org.h2.twopc.TwoPCRequest(this);
      result.command_ = command_;
      result.db_ = db_;
      result.table_ = table_;
      result.sid_ = sid_;
      result.tid_ = tid_;
      result.data_ = data_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.h2.twopc.TwoPCRequest) {
        return mergeFrom((org.h2.twopc.TwoPCRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.h2.twopc.TwoPCRequest other) {
      if (other == org.h2.twopc.TwoPCRequest.getDefaultInstance()) return this;
      if (!other.getCommand().isEmpty()) {
        command_ = other.command_;
        onChanged();
      }
      if (!other.getDb().isEmpty()) {
        db_ = other.db_;
        onChanged();
      }
      if (!other.getTable().isEmpty()) {
        table_ = other.table_;
        onChanged();
      }
      if (!other.getSid().isEmpty()) {
        sid_ = other.sid_;
        onChanged();
      }
      if (!other.getTid().isEmpty()) {
        tid_ = other.tid_;
        onChanged();
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.h2.twopc.TwoPCRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.h2.twopc.TwoPCRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object command_ = "";
    /**
     * <code>string command = 1;</code>
     * @return The command.
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string command = 1;</code>
     * @return The bytes for command.
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = getDefaultInstance().getCommand();
      onChanged();
      return this;
    }
    /**
     * <code>string command = 1;</code>
     * @param value The bytes for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      command_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object db_ = "";
    /**
     * <code>string db = 2;</code>
     * @return The db.
     */
    public java.lang.String getDb() {
      java.lang.Object ref = db_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        db_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string db = 2;</code>
     * @return The bytes for db.
     */
    public com.google.protobuf.ByteString
        getDbBytes() {
      java.lang.Object ref = db_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        db_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string db = 2;</code>
     * @param value The db to set.
     * @return This builder for chaining.
     */
    public Builder setDb(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      db_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string db = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDb() {
      
      db_ = getDefaultInstance().getDb();
      onChanged();
      return this;
    }
    /**
     * <code>string db = 2;</code>
     * @param value The bytes for db to set.
     * @return This builder for chaining.
     */
    public Builder setDbBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      db_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object table_ = "";
    /**
     * <code>string table = 3;</code>
     * @return The table.
     */
    public java.lang.String getTable() {
      java.lang.Object ref = table_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        table_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string table = 3;</code>
     * @return The bytes for table.
     */
    public com.google.protobuf.ByteString
        getTableBytes() {
      java.lang.Object ref = table_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string table = 3;</code>
     * @param value The table to set.
     * @return This builder for chaining.
     */
    public Builder setTable(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      table_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string table = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTable() {
      
      table_ = getDefaultInstance().getTable();
      onChanged();
      return this;
    }
    /**
     * <code>string table = 3;</code>
     * @param value The bytes for table to set.
     * @return This builder for chaining.
     */
    public Builder setTableBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      table_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sid_ = "";
    /**
     * <code>string sid = 4;</code>
     * @return The sid.
     */
    public java.lang.String getSid() {
      java.lang.Object ref = sid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sid = 4;</code>
     * @return The bytes for sid.
     */
    public com.google.protobuf.ByteString
        getSidBytes() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sid = 4;</code>
     * @param value The sid to set.
     * @return This builder for chaining.
     */
    public Builder setSid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sid = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSid() {
      
      sid_ = getDefaultInstance().getSid();
      onChanged();
      return this;
    }
    /**
     * <code>string sid = 4;</code>
     * @param value The bytes for sid to set.
     * @return This builder for chaining.
     */
    public Builder setSidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tid_ = "";
    /**
     * <pre>
     *TODO: change tid to long
     * </pre>
     *
     * <code>string tid = 5;</code>
     * @return The tid.
     */
    public java.lang.String getTid() {
      java.lang.Object ref = tid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *TODO: change tid to long
     * </pre>
     *
     * <code>string tid = 5;</code>
     * @return The bytes for tid.
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *TODO: change tid to long
     * </pre>
     *
     * <code>string tid = 5;</code>
     * @param value The tid to set.
     * @return This builder for chaining.
     */
    public Builder setTid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *TODO: change tid to long
     * </pre>
     *
     * <code>string tid = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTid() {
      
      tid_ = getDefaultInstance().getTid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *TODO: change tid to long
     * </pre>
     *
     * <code>string tid = 5;</code>
     * @param value The bytes for tid to set.
     * @return This builder for chaining.
     */
    public Builder setTidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tid_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 6;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:twopc.TwoPCRequest)
  }

  // @@protoc_insertion_point(class_scope:twopc.TwoPCRequest)
  private static final org.h2.twopc.TwoPCRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.h2.twopc.TwoPCRequest();
  }

  public static org.h2.twopc.TwoPCRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TwoPCRequest>
      PARSER = new com.google.protobuf.AbstractParser<TwoPCRequest>() {
    @java.lang.Override
    public TwoPCRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TwoPCRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TwoPCRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TwoPCRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.h2.twopc.TwoPCRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

