// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: twopc.proto

package org.h2.twopc;

public interface TwoPCRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:twopc.TwoPCRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>string db = 2;</code>
   * @return The db.
   */
  java.lang.String getDb();
  /**
   * <code>string db = 2;</code>
   * @return The bytes for db.
   */
  com.google.protobuf.ByteString
      getDbBytes();

  /**
   * <code>string table = 3;</code>
   * @return The table.
   */
  java.lang.String getTable();
  /**
   * <code>string table = 3;</code>
   * @return The bytes for table.
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>string sid = 4;</code>
   * @return The sid.
   */
  java.lang.String getSid();
  /**
   * <code>string sid = 4;</code>
   * @return The bytes for sid.
   */
  com.google.protobuf.ByteString
      getSidBytes();

  /**
   * <pre>
   *TODO: change tid to long
   * </pre>
   *
   * <code>int64 tid = 5;</code>
   * @return The tid.
   */
  long getTid();

  /**
   * <code>int32 hid = 6;</code>
   * @return The hid.
   */
  int getHid();

  /**
   * <code>bytes data = 7;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
